package br.study.mixing.base64.table.unicode;

import br.study.mixing.base64.table.TableInfo;
import br.study.mixing.base64.table.TableList;
import lombok.Data;

import java.util.List;

@Data
public class UnicodeTable extends TableList {

    public List<TableInfo> getBasicLetters() {
        return List.of(
            new TableInfo(32, ' '),
            new TableInfo(33, '!'),
            new TableInfo(34, '"'),
            new TableInfo(35, '#'),
            new TableInfo(36, '$'),
            new TableInfo(37, '%'),
            new TableInfo(38, '&'),
            new TableInfo(39, '\''),
            new TableInfo(40, '('),
            new TableInfo(41, ')'),
            new TableInfo(42, '*'),
            new TableInfo(43, '+'),
            new TableInfo(44, ','),
            new TableInfo(45, '-'),
            new TableInfo(46, '.'),
            new TableInfo(47, '/'),
            new TableInfo(48, '0'),
            new TableInfo(49, '1'),
            new TableInfo(50, '2'),
            new TableInfo(51, '3'),
            new TableInfo(52, '4'),
            new TableInfo(53, '5'),
            new TableInfo(54, '6'),
            new TableInfo(55, '7'),
            new TableInfo(56, '8'),
            new TableInfo(57, '9'),
            new TableInfo(58, ':'),
            new TableInfo(59, ';'),
            new TableInfo(60, '<'),
            new TableInfo(61, '='),
            new TableInfo(62, '>'),
            new TableInfo(63, '?'),
            new TableInfo(64, '@'),
            new TableInfo(65, 'A'),
            new TableInfo(66, 'B'),
            new TableInfo(67, 'C'),
            new TableInfo(68, 'D'),
            new TableInfo(69, 'E'),
            new TableInfo(70, 'F'),
            new TableInfo(71, 'G'),
            new TableInfo(72, 'H'),
            new TableInfo(73, 'I'),
            new TableInfo(74, 'J'),
            new TableInfo(75, 'K'),
            new TableInfo(76, 'L'),
            new TableInfo(77, 'M'),
            new TableInfo(78, 'N'),
            new TableInfo(79, 'O'),
            new TableInfo(80, 'P'),
            new TableInfo(81, 'Q'),
            new TableInfo(82, 'R'),
            new TableInfo(83, 'S'),
            new TableInfo(84, 'T'),
            new TableInfo(85, 'U'),
            new TableInfo(86, 'V'),
            new TableInfo(87, 'W'),
            new TableInfo(88, 'X'),
            new TableInfo(89, 'Y'),
            new TableInfo(90, 'Z'),
            new TableInfo(91, '['),
            new TableInfo(92, '\\'),
            new TableInfo(93, ']'),
            new TableInfo(94, '^'),
            new TableInfo(95, '_'),
            new TableInfo(96, '`'),
            new TableInfo(97, 'a'),
            new TableInfo(98, 'b'),
            new TableInfo(99, 'c'),
            new TableInfo(100,	'd'),
            new TableInfo(101,	'e'),
            new TableInfo(102,	'f'),
            new TableInfo(103,	'g'),
            new TableInfo(104,	'h'),
            new TableInfo(105,	'i'),
            new TableInfo(106,	'j'),
            new TableInfo(107,	'k'),
            new TableInfo(108,	'l'),
            new TableInfo(109,	'm'),
            new TableInfo(110,	'n'),
            new TableInfo(111,	'o'),
            new TableInfo(112,	'p'),
            new TableInfo(113,	'q'),
            new TableInfo(114,	'r'),
            new TableInfo(115,	's'),
            new TableInfo(116,	't'),
            new TableInfo(117,	'u'),
            new TableInfo(118,	'v'),
            new TableInfo(119,	'w'),
            new TableInfo(120,	'x'),
            new TableInfo(121,	'y'),
            new TableInfo(122,	'z'),
            new TableInfo(123,	'{'),
            new TableInfo(124,	'|'),
            new TableInfo(125,	'}'),
            new TableInfo(126,	'~')
        );
    }
}
